# Copy this file to config.yaml
# config.yaml is ignored in .gitignore
# Change the below keys to correspond with the values for Google Analytics and
# Google Web Master Tools
trackingCode: UA-8594346-12
trackingDomain: angulardart.org 
